### ISSUE TITLE
rumble on remote control

### ISSUE THREAD

**Issue by frranck** [Javanaise/mrboom-libretro#113]
Based on SameBoy, it should be semi-minor.
https://github.com/LIJI32/SameBoy/blob/6b30de5fb1c9c7c177ea544db9fe82e7d40a2171/Core/rumble.c
https://github.com/LIJI32/SameBoy/blob/195329463b0927c6e9bf13ea2aceb849b5301bb1/Core/rumble.h
https://github.com/LIJI32/SameBoy/blob/bdd27ce50d4b27898e11e8a34c9371e210f10846/libretro/libretro.c

The trick is how to modulate the rumble amplitude.
`rumble.set_rumble_state(0, RETRO_RUMBLE_STRONG, 65535 * amplitude);`

If you do that, you mightest as well add achivements also. Come up with simple and hard badges to get people to player longer.

_Originally posted by @SimpleTease in https://github.com/Javanaise/mrboom-libretro/issues/108#issuecomment-751474359_

**Comment by SimpleTease** [comment]
For amplitude, we could read the waveform for bomb explosion. Convert down to 60Hz and apply rumble. I don't have a rumble pad so can't realistically test, unless there's libretro way to shake screen or something.
