### ISSUE TITLE
How to edit graphics and level data?

### ISSUE THREAD

**Issue by gzuk78** [Javanaise/mrboom-libretro#117]
Is there any way to edit graphics and level data for the game?

The tools/data/GFX folder contains PCX files, but I have not found any way to open them with graphics editors. In theory, Gimp should be able to open standard "Picture Exchange" files, but it didn't work for me.

* Gimp error message is: "CRAYON.PCX is not a PCX file"
* LibreSprite error message is: "This PCX doesn't have 8 bit color planes"

What program do you use to edit the graphics files?

Many thanks for an answer! 🙂

**Comment by frranck** [comment]
hi @gzuk78  maybe Grafx2 does it, but It's gonna be extremely tricky, you would need to modify the assembly data files also... it's probably not the easiest project to create skins for...

**Comment by gzuk78** [comment]
Thanks for the suggestion, but no luck with Grafx2 either. There must be some non-standard feature about those PCX files. How did you guys actually manage to edit them? Or did you just inherit them as-is from an old DOS version or something?

If this project is un-skinnable, do you maybe happen to know a better-suited Bomberman clone (with MrBoom features like monsters, 4-directions characters, animal mounts etc.)?

**Comment by frranck** [comment]
I remember now, the headers have been patched...
You should check other projects with the bomberman tag https://github.com/topics/bomberman like https://github.com/bjaraujo/Bombermaaan
