### ISSUE TITLE
Mr. Boom on Raspberry Pi 4 on Lakka - Only 5 players supported?

### ISSUE THREAD

**Issue by mtoensing** [Javanaise/mrboom-libretro#118]
I installed Lakka on a Pi4 and I got 6 controllers showing up. But in Mr Boom the sixth controller would not accept "fire" button. But the controller is okay because if I switch it on at the start then the last sixth controller won't work. Is this a bug.

**Comment by frranck** [comment]
Hello Marc, so that's the libretro version right? Could you please check the sdl2 version?

**Comment by mtoensing** [comment]
How do I do this? It is the official repository here https://github.com/libretro/Lakka-LibreELEC

**Comment by frranck** [comment]
Install one of those packages https://repology.org/project/mrboom/versions that doesn't have libretro in its name or compile it https://github.com/Javanaise/mrboom-libretro#compiling-the-sdl2-version
I already played with more that 5 pads with the SDL2 version so I suppose it's a retroarch bug.

**Comment by frranck** [comment]
I would try on your OSX or windows machine if you can plug the pads there.

**Comment by mtoensing** [comment]
Ok, I thought that Lakka is the official solution for RetroArch on a Pi and MrBoom is made for Libreto. I don't want to use my Mac or compile it myself to run it on the pi. Shouldn't the people who maintain Lakka solve this in their repository? Does it help if I open an issue there?

**Comment by frranck** [comment]
Yes please open an issue there, that link this one.

**Comment by StormedBubbles** [comment]
Do you have the max users set to 8 in `Main Menu -> Settings -> Input`?

**Comment by frranck** [comment]
any update @mtoensing ?

**Comment by frranck** [comment]
Yeah but that can only to be fixed in RetroArch so we need an issue there  https://github.com/libretro/RetroArch/issues I suppose

**Comment by StormedBubbles** [comment]
The default number for the max may be dependent on where you obtained RetroArch from. In RetroPie, the default is 5. In Windows, I have two retroarch.cfg files. One of them has 5, but the other, labeled as "default," has 16 as the max. Unless you have some core- or content-specific overrides defining a different number, you can just change the number in `input_max_users = "5"` in the global retroarch.cfg to the max number of users you want (16 seems to be the highest).
