### ISSUE TITLE
The game works sooooo fast, like a turbo mode

### ISSUE THREAD

**Issue by scyther149** [Javanaise/mrboom-libretro#119]
i can't play, the game works in a turbo mode and it's imposible hahah
i have a good pc, rtx3080ti, i don't know how to fix this, i didn't found a solution :c

**Comment by frranck** [comment]
In which distribution are you playing it?

**Comment by scyther149** [comment]
> In which distribution are you playing it?

what do you mean with Distribution?
I have w11 pro 64bits
Ryzen 7 5800x
rtx 3080ti
32gb ram

**Comment by frranck** [comment]
like how did you install the game? retrolib or SDL2?

**Comment by scyther149** [comment]
> like how did you install the game? retrolib or SDL2?

i downloaded it here

![image](https://github.com/Javanaise/mrboom-libretro/assets/93342262/5cfeb11a-b617-4371-927f-34cab891b8d0)

i unzipped it and runned it like admin

**Comment by frranck** [comment]
Could it be because you don't switch to full screen?

**Comment by frranck** [comment]
otherwise try to run it through [retroarch](https://www.retroarch.com/).

**Comment by scyther149** [comment]
> otherwise try to run it through [retroarch](https://www.retroarch.com/).

this works fine! Thank youuuu <3
(my girlfriend won :c hahahha)

**Comment by frranck** [comment]
and in full screen the other version was still too fast?
