### ISSUE TITLE
Immediately crash dumps when starting core if logging is set to 1 (Info) or below

### ISSUE THREAD

**Issue by vaguerant** [Javanaise/mrboom-libretro#123]
Running libretro/RetroArch@4f8e3fa and mrboom-libretro 089b91d.

The core itself starts up (i.e. the RetroArch menu), but selecting Start Core crashes the console as below:

![DSI exception screen](https://github.com/Javanaise/mrboom-libretro/assets/5259025/85e8bb99-057f-4fc2-a81e-dc68b2c463d3)

Disabling logging via Settings > Logging from the RetroArch menu prevents this crash from occurring.

**Comment by frranck** [comment]
Hello,
maybe some empty value there https://github.com/Javanaise/mrboom-libretro/blob/master/libretro/retro.cpp#L123

**Comment by frranck** [comment]
Could you please update and check if it still fails with logs?

**Comment by vaguerant** [comment]
Updated to c10355e, sorry to report that the same issue still occurs.

**Comment by LibretroAdmin** [comment]
Does this happen with any core when logging is enabled / set to Level 1 or only with this core?

**Comment by vaguerant** [comment]
Only this core in my testing. I tested other "normal" cores like pcsx-reARMed as well as contentless cores like VICE x64 and 2048 which run via Start Core. None of the other cores have any issue.

**Comment by Apaczer** [comment]
Yes I can confirm it SEGFAULTs when you run from `retroarch -v -L mrboom_libretro.so` cmd, but without verbose it runs ok.

**Comment by frranck** [comment]
seems this is fixing it https://github.com/Javanaise/mrboom-libretro/commit/20244a75910802b22690407750189f837682c68e

**Comment by Apaczer** [comment]
> seems this is fixing it https://github.com/Javanaise/mrboom-libretro/commit/20244a75910802b22690407750189f837682c68e

It does! Be it logging from RA menu or cmd line there is no crash. GJ :+1:
