### ISSUE TITLE
Makefile will need an update to support new Wii U toolchain

### ISSUE THREAD

**Issue by vaguerant** [Javanaise/mrboom-libretro#127]
libretro/RetroArch#14925 will be updating RetroArch to compile with the modern Wii U toolchain instead of the old version with which it builds currently. In the time since libretro updated the toolchain, the `-mwup` flag was removed from the compiler. @Ploggy has already submitted a PR libretro/mrboom-libretro#28 against the libretro fork which supports both toolchain versions, but I'm not sure whether development occurs here or there, so just covering all bases in case it needs to be merged over here first or synced from there after merge, etc.

**Comment by frranck** [comment]
@vaguerant Hello, I will merge it.
