### ISSUE TITLE
Cannot launch on SteamOS / BPM -seg fault

### ISSUE THREAD

**Issue by mdeguzis** [Javanaise/mrboom-libretro#14]
OS: SteamOS
GPU: Nvidia GTX 1080
Driver: nvidia

This runs fine (albeit starting in a small window) in Gnome 3 desktop mode, but not in BPM where SteamOS starts up in. Puzzling. Any launch options I can use for debugging as well? I am using the non-libretro core makefile target to play on a traditional Linux desktop.

Log:
https://gist.github.com/mdeguzis/87d874c653fd7284507680f36df5a939

**Comment by frranck** [comment]
Hi, could you try to compile it ? 
```
make clean
make mrboom LIBSDL2=1
```

**Comment by mdeguzis** [comment]
I'm using the same packaging Debian games maintainers are. If there is a way to debug the game with a flag, I can add that at runtime so /tmp/dump/steam_stdout.txt can log it.

https://github.com/mdeguzis/LibreGeek-Packaging/tree/steamos/mrboom

**Comment by frranck** [comment]
Could it be it can't write to /tmp/ ?

**Comment by frranck** [comment]
Did you google "ERROR: ld.so: object '/home/steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
" ?

**Comment by mdeguzis** [comment]
temp is a possibility, what file/path? The ELF stuff is normal under SteamOS. Valve submits 32/64 libs and one is always going to come up funny like that, and just ignored (as it says).

**Comment by mdeguzis** [comment]
It was /tmp. If you know the path, I can try to make an ACL, however, it would be nice to nip this in the butt and allow a switch to redirect the tmp (logs?) data elsewhere.

**Comment by frranck** [comment]
It's game data, it's creating a /tmp/mrboom directory, do you need the list of the files ? I can add a command line option in the next version.

**Comment by mdeguzis** [comment]
I probably don't need a list of files, but if that can be redirected to a users $HOME or something, that would help. Several distros, such as CentOS, RedHat, SteamOS etc... have default users with limited access to /tmp. While /tmp is fine, it would be nice to redirect that. For now I created that directory and allowed permission to it. Not pressing then, but a good thing to add in a future build.

**Comment by frranck** [comment]
Hi, can you try the current master?

**Comment by mdeguzis** [comment]
Sure, I'll rebuild and try tomorrow. I was previously building master assume you added a potential fix.

**Comment by mdeguzis** [comment]
No issue now on master. closing.
