### ISSUE TITLE
De-C++11ify this

### ISSUE THREAD

**Issue by twinaphex** [Javanaise/mrboom-libretro#16]
@frranck 

In case you couldn't tell by my comments,

I really, really do not like how you forced C+11 now on this codebase.

This means that it will not compile for PS3, Blackberry, Xbox OG, 360, ever, whereas before there was this possibility.

At the very least add the C++11 portions behind an ifdef so that I can still compile this without needing a C++11 compiler, or better yet, rewrite the C+11 portions to C++98 so that I still have a solution on other platforms.

Oh, and it does not compile for iOS versions below 8.0 anymore.

I really consider this a very negative regression and not an improvement at all. Please reconsider, this is terrible.

**Comment by frranck** [comment]
Dammit, is there an easy way to have the buildbots testing a develop branch without shipping a new version into retroarch ?

**Comment by twinaphex** [comment]
We'd have to ask either @fr500 or @bparker06. @bparker06 specifically has more control over the buildbot server these days and could possibly field a request on your end.

**Comment by alexmyczko** [comment]
someone is building an iOS version of mrboom? how to control the character? voice control? "left, left, right, up, down. BOMB!?" haha

**Comment by frranck** [comment]
Fixed, thanks for your bug report @twinaphex
