### ISSUE TITLE
Install on recalbox?

### ISSUE THREAD

**Issue by Benance** [Javanaise/mrboom-libretro#27]
Hello
Is there a way to (simply) install Mr boom on recalbox?
Thanks for your answers.

**Comment by frranck** [comment]
Hi, I don't know recalbox, maybe you could open an issue there ?

**Comment by Benance** [comment]
Thanks for your answer.
Recalbox is an emulation-dedicated small operating system running libretro/retroarch as backend (that's why I created an issue here) and emulationstation as frontend.
More infos available here: https://www.recalbox.com/

**Comment by rockaddicted** [comment]
Hi @Benance,   
it is a recalbox issue, not one related to the core development.
An issue is already open on our repo. https://gitlab.com/recalbox/recalbox/issues/257
It is planned to it in the futur.

This issue can be closed.
