### ISSUE TITLE
git pull takes a long time

### ISSUE THREAD

**Issue by kenden** [Javanaise/mrboom-libretro#31]
When there are large files in the repository, it can take a long time to do a `git pull` on the repository.
https://stackoverflow.com/questions/7731785/git-stuck-on-unpacking-objects-phase

Making big files smaller would help with this:

```
$ du -hs *    
272K	ai
184K	Assets
4,0K	circle.yml
24K	common.cpp
4,0K	common.hpp
756K	common.o
12K	jni
788K	libretro-common
88K	libretro.h
4,0K	LICENSE
4,0K	link.T
12K	Makefile
4,0K	Makefile.common
22M	mrboom.c       <------------ this
112K	mrboom.h
5,0M	mrboom.o
5,7M	mrboom.out
4,0K	README.md
16K	retro.cpp
6,5M	retro_data.h    <------ this
4,0K	retro.hpp
304K	sdl2
3,8M	sdl2_data.h
15M	tests
```

**Comment by frranck** [comment]
Sorry it would require too much efforts to improve that... Will close that one.
