### ISSUE TITLE
Compilation error MSVC 2003 (for PC and Xbox OG)

### ISSUE THREAD

**Issue by twinaphex** [Javanaise/mrboom-libretro#32]
If we can fix this, we could make this game work on the original Xbox.

Log here -

https://hastebin.com/vuwomegula.pas

**Comment by frranck** [comment]
@twinaphex Just pushed, let me know if that works now...

**Comment by frranck** [comment]
Forgot the changes in mrboom.h will push again in a bit...

**Comment by twinaphex** [comment]
Now I get this error -

mrboom.c(119307) : warning C4295: 'heap57' : array is too small to include a ter                                                                                            minating null character
mrboom.c(121279) : fatal error C1060: compiler is out of heap space

**Comment by frranck** [comment]
funny to get an heap error with the heap variable. Isn't C4295 is caused by C1060 ?
microsoft gives some solution for C1060:
https://msdn.microsoft.com/en-us/library/yz7kx3y2.aspx

**Comment by frranck** [comment]
@twinaphex I tried to fix the problem by loading the data from the files like in the SDL2 version. 
This is adding a minizip dependancy and I've got error with 16.WAV and 17.WAV. 
Could you give it a try ?

**Comment by frranck** [comment]
Fixed the 16.WAV and 17.WAV problem...

**Comment by frranck** [comment]
@twinaphex Any update on that one ?
Also: could you please put a bounty on that ? https://github.com/libretro/libretro-common/issues/34#issuecomment-391437454 … I couldn't figure out...

**Comment by SimpleTease** [comment]
I created a working build with 2003.
https://github.com/SimpleTease/mrboom-libretro/commit/59e41991528a32fea79cbc959a77fc88eba83ef9

0. minizip dependency
1. net files have to load before mrboom.h
2. compat_snprintf
3. converted sdl2_data.h to avoid 65536 string limit
4. copied a bunch of 2003 makefile stuff from other libretro projects
5. mrboom.h
- doesn't understand `__attribute__ ((__packed__));`
- some `int x,y` moved out of loop headers

Music and gameplay okay.

I do have one problem though: when going to Retroarch menu while in-game, it freezes. Debugger suggests XAudio is stuck waiting for something but I'm not sure.

Could be this line is mistake.
https://github.com/SimpleTease/mrboom-libretro/commit/59e41991528a32fea79cbc959a77fc88eba83ef9#diff-4c7efb8ec878d49060539d3e5294eb67358d3134333be0b537df51e40d448b5aR733

**Comment by twinaphex** [comment]
Hi @SimpleTease , did you send a PR for this to either the libretro repo or Javanaise?

**Comment by SimpleTease** [comment]
Not yet ready because I'm making extra changes like adjusting formatting and modifying compiler flags. I found a fix for the 2003 crashing but 2005 has some unique libretro-common/net compiler problems. So I want to make sure it's fully ready before sending off the PR.

I'll probably add it up here to Javanaise when I feel it's convenient.

**Comment by frranck** [comment]
so can this one be closed?

**Comment by SimpleTease** [comment]
Tried msvc buildbot and it works. So ticket can be closed.
