### ISSUE TITLE
SDL2: The joystick does not work properly

### ISSUE THREAD

**Issue by goupildb** [Javanaise/mrboom-libretro#33]
Hi,
My joystick (Logitech Rumblepad) does not work properly.
The digital stick works well, but the analog stick does not work properly.
The problem : the scale of response of the game to the movement of the analog stick is too short or nonexistent (for example I put the analog stick completely to the right and sometimes it does not respond).

I think its a problem with the game and not with SDL, because with other games (Bombermaaan for example, which use SDL too) my joystick works fine.

**Comment by frranck** [comment]
Hi @goupildb , could you please try again with current master ?

**Comment by goupildb** [comment]
It works!
There are sometimes some small lags with the joystick, but it works, it's much more playable
Thank you very much
Resolved!
