### ISSUE TITLE
Compilation fails on Windows x64

### ISSUE THREAD

**Issue by twinaphex** [Javanaise/mrboom-libretro#35]
See this log -

<retrobot> mrboom: [status: fail] [recipes/windows/cores-windows-x64_seh-generic] LOG: http://p.0bl.net/4998

Let me know if you are able to see these build errors yourself and you would appreciate me not pointing this out, whatever works best for you.

**Comment by frranck** [comment]
Hi, 
I have access the build bot, but it's good to get notified here.
Any update on this one ? https://github.com/Javanaise/mrboom-libretro/issues/32
There are some missing WAV to be added to the libretro version, but that will make the data even bigger...
