### ISSUE TITLE
Could you make it possible for the user to add user created sprites?

### ISSUE THREAD

**Issue by zanzabarjones** [Javanaise/mrboom-libretro#39]
mrboom is a beautiful game but it would be even more amazing if the user could use their own sprites..like Link from the legend of Zelda as Mr Boom or even Bugs Bunny or completely user generated sprites..

**Comment by frranck** [comment]
Hi Zanzabar, that's a bit tricky because of the game assembly code history. The sprites would need to use a very specific palette, positioning and very low resolution. If someone provided good sprites I would figure out a way, but I don't think it make sense to spend time on this before...

**Comment by SimpleTease** [comment]
If someone found the asm that loaded the pcx and then used a redirector to load custom gifs instead, would that get anywhere? Have no idea about the palette hacking though.
https://github.com/bparker06/mrboom30

**Comment by frranck** [comment]
The sdl2 version still decrunchs the pcx into memory, it's unzipping some data files, the retrolib version is using a dump from the memory, so that it doesn't need to do that. That was an issue for some platforms...
