### ISSUE TITLE
libretro-common folder of release 5.0 is empty

### ISSUE THREAD

**Issue by Moisan** [Javanaise/mrboom-libretro#49]
The 5.0 release has a `libretro-common`, hence compilation from source fails.

**Comment by SimpleTease** [comment]
When building, I had to `git submodule update --init --recursive` to pull the `libretro-common` files from `https://github.com/libretro/libretro-common/tree/fedb955ff18465d879b8bb02c7e6fc17188780b1`

I wonder if there's another way though.

**Comment by frranck** [comment]
Hello, 
I added MrBoom-src-5.0.tar.gz and MrBoom-src-5.0.zip in the release assets, that includes the submodule, maybe you could use one  of those?

**Comment by Moisan** [comment]
@frranck thank you, this fixes the issue!
