### ISSUE TITLE
libretro feature request - disable netplay option

### ISSUE THREAD

**Issue by SimpleTease** [Javanaise/mrboom-libretro#52]
Hi, I'm behind a firewall that blocks out packets and core just hangs for awhile until it timeout. So asking for a run-time core option that can skip netplay check at core bootup when desired.

**Comment by frranck** [comment]
Those are stats, so I guess we could change the timeout to 1 second.

**Comment by SimpleTease** [comment]
Or shorter timeouts and more net checks could work too.

**Comment by SimpleTease** [comment]
Or non-blocking thread on platforms that support.

**Comment by SimpleTease** [comment]
I created another build that has netplay disabled and I just switch between the two when needed.
