### ISSUE TITLE
skynet status screen

### ISSUE THREAD

**Issue by SimpleTease** [Javanaise/mrboom-libretro#54]
I think it'd be more helpful if the Skynet post-round screen has just 1 for Humans and 1 for Bots, instead of everyone. Like how the Gender team mode displays the score card.

**Comment by frranck** [comment]
Graphics parts are tricky to change because the game is a hack from an assembly version.

**Comment by SimpleTease** [comment]
Also realized that fitting 7 Skynet names under 1 icon wouldn't work well. Maybe giving all Humans or Bots a medal could make sense but the asm again, that would be trouble. I'll close this since it seems realistically not feasible.
