### ISSUE TITLE
select aspect ratio

### ISSUE THREAD

**Issue by SimpleTease** [Javanaise/mrboom-libretro#56]
I think there should be options to change aspect ratio
- 16:10 (native)
- 4:3 (crt)
- 16:9 (wide)

Libretro stretches to 16:9 and I think default should be changed to 16:10 (320x200).

**Comment by frranck** [comment]
It's there, 
https://github.com/Javanaise/mrboom-libretro/blob/d7e4dbbe19f2c88355369328e50bd1def91dc674/retro.cpp#L177 and there's also the sample rate around...

**Comment by SimpleTease** [comment]
I was thinking of an adjustable run-time option like the C64, Snes and other cores. I'll play around with the code when I get a chance.
