### ISSUE TITLE
libretro sfx little fast?

### ISSUE THREAD

**Issue by SimpleTease** [Javanaise/mrboom-libretro#58]
I noticed that the sdl raw wave files are @ 44100 but libretro plays them at 48000 so they sound slightly sped up (8%). Is there way to 1-shot upsample them using libretro-common resampler?

**Comment by frranck** [comment]
not sure, but libretro is not using the same files than sdl, it's using data from here https://github.com/Javanaise/mrboom-libretro/blob/master/retro_data.h

**Comment by SimpleTease** [comment]
Was using LOAD_FROM_FILES for my own external customizations but I'll check that retro file too and try to figure out the sound rate.

**Comment by SimpleTease** [comment]
I did the math and retro_data.h is 48000 16-bit stereo. Frontend was adding some latency and maybe the upsample added some too. Libretro does sound slower now at 44100 vs 48000 so I guess should revert the change.
https://github.com/Javanaise/mrboom-libretro/commit/f650c14251bffea21e34c396bb637cc4a9aa2a84#diff-815b414bb91f23155827e50a78efdae23e3ed87e63fc47c1b99d2858338f301bL74

Must be my error somewhere because it was sounding a little distorted but formulas show otherwise. I'll figure it out for myself.
