### ISSUE TITLE
Button autofire by default

### ISSUE THREAD

**Issue by Tatsuya79** [Javanaise/mrboom-libretro#6]
When entering your initials on the start screen, the validate button is in autofire mode making it tricky to input letters.

In the game as well, auto-dropping several bombs in rapid successions should perhaps not be the default.
We have a turbo button mode in retroarch for this or it could be assigned to an additional input button.

**Comment by frranck** [comment]
You don't drop bomb by default, I guess you have a input issue...

**Comment by Tatsuya79** [comment]
I mean when you keep the button pushed down and walk it will drop several bombs.
Bomberman games usually wait for you to push the button again to drop a second bomb.

**Comment by frranck** [comment]
for the menu: use left and right instead 
for the bomb dropping game itself, I think dynablaster PC was doing the same, and I prefer it that way...

**Comment by frranck** [comment]
Had a second thought about the menu, you're quite right, will improve that in the next versions.

**Comment by frranck** [comment]
I increased the change blocker time from 10 to 15. have a look in current version...

**Comment by Tatsuya79** [comment]
I compiled it at the buildbot isn't updated.
Well, that's better on the menu screen.
But I don't understand why you're not letting the players decide their play-style:
if you disable autofire in-game, players can use libretro autofire.

Personally I keep throwing unwanted bombs which feels frustrating.
I think this could deserve your game.

**Comment by Tatsuya79** [comment]
You just need to disable the autofire happening in MrBoom code itself.
Then there is a Turbo button mode in Retroarch that can be used.
Or you can add a turbo button directly on the gamepad [with a code like this one for Nestopia.](https://github.com/libretro/nestopia/commit/4085e3138735e302a5588f0e37dedd21223a4a89)
[(along with this fix if needed?)](https://github.com/libretro/nestopia/commit/091f5a5889c51c1d0dc7c433a79d4f318420fef3)

**Comment by frranck** [comment]
Yeah but I don't want to change the B button behaviour, I prefer it that way. Maybe you just need to get used to it.

**Comment by barbudreadmon** [comment]
Played it (locally) for the first time with 5 friends yesterday, they all complained about the B button behavior (we are all in our late thirties and have been playing bombermans together since the snes era).

I can understand you prefer it that way, but since it is not the behavior in any bomberman i played (and i played most of them), making it a core option would be nice. You can't get used to it when you played thousands of bomberman rounds.

Actually, there is one other thing i would make a core option if possible : the monsters. Depending on your luck, you can be screwed from the very beginning because of them.

**Comment by twinaphex** [comment]
I have to agree with @barbudreadmon too, I thought the B button behavior was a glitch at first.

I think it would be sensible to use normal Bomberman default B button behavior and then make it possible (perhaps via a core option) to turn the 'current' behavior on optionally. The other way around is confusing and perhaps backfires with most people used to Bomberman.

**Comment by frranck** [comment]
Guys I just tried Super Bomberman 3 on Snes, and it has the Mr.Boom behaviour:
If you push the B button and keep it pushed, you keep dropping bombs.

How do the core options work ?

**Comment by Tatsuya79** [comment]
To my great surprise there was an autofire in every NEC games, starting from the 3rd on SNES.
Guess it's just slower and not noticeable there.

**Comment by barbudreadmon** [comment]
Makes sense, i think i own the first on every console, starting with snes. I tried a few others through emulation, but never spent much time on those.

**Comment by barbudreadmon** [comment]
About how the core options works, take a look at the core i'm maintaining :  https://github.com/libretro/fbalpha/blob/master/src/burner/libretro/libretro.cpp

Lines 158-177 = how to declare them
Lines 651-718 = how to send them to retroarch
Lines 1115-1307 = how to retrieve what was selected in retroarch

I hope it helps.

**Comment by barbudreadmon** [comment]
@frranck So, any news about this core option ? I wouldn't mind creating a pull request if you tell me where i can change this behavior.

**Comment by frranck** [comment]
@barbudreadmon It's a bit tricky because it touches the assembly code. I'm working on some bomberman AI now, that includes some "assembly wrapper" functions, so I will have a look afterwards.

**Comment by frranck** [comment]
How can this work with netplay ? The option must be the same on all computers, otherwise it's going to desynchronise...

**Comment by barbudreadmon** [comment]
Well, if you can't make it an option, then i suggest you make it the default, i played more than a third of the (33) bomberman games, probably the most well-known, and none of them had this autofire behavior.
Over that, perhaps you could add some kind of client-side per gamepad hack like @Tatsuya79 mentioned

**Comment by twinaphex** [comment]
I second this by barbudreadmon.

Despite what you might think, to most gamers this will just be annoying and they will regard the game as being broken. Please consider implementing this as an option instead.

**Comment by frranck** [comment]
@twinaphex Having global options is an issue that needs to be fixed with netplay, it's gonna be the same problem on every core... There could be a way to hack it, if I put a frame counter in the state to spot rewinds on slaves, and then ignore the options from retroarch and use the options values from the state.

**Comment by frranck** [comment]
Hello, I just pushed the long awaited autofire = off option... 
I'd like to get some proper testing and feedback before deciding its default value.

**Comment by Tatsuya79** [comment]
Thank you! seems to be working fine (just tried single player). :)
