### ISSUE TITLE
isAIActiveForPlayer not correct?

### ISSUE THREAD

**Issue by SimpleTease** [Javanaise/mrboom-libretro#60]
From recent master.
https://github.com/Javanaise/mrboom-libretro/blob/e074bafa1fe9480df1ba412752912a2c2c454958/ai/MrboomHelper.cpp#L122

Bots are bit 6? (64-127)
Monsters are bit 7? (128-255)

I don't think it affects anything but just for correctness.

**Comment by frranck** [comment]
Not sure, this is looking for bombermen AI, the Monsters AI is in the assembly code. The C++ layer is injecting keys input for the AI, there used to be some IPX network code... https://github.com/bparker06/mrboom30

**Comment by frranck** [comment]
Anyway this function is probably correct.

**Comment by SimpleTease** [comment]
Alright! I was suspicious that it was maybe `(m.control_joueur[player] < 64 * 2)` but guess not. Just asking to be safe. :)
