### ISSUE TITLE
ai victories error?

### ISSUE THREAD

**Issue by SimpleTease** [Javanaise/mrboom-libretro#61]
https://github.com/Javanaise/mrboom-libretro/blob/e074bafa1fe9480df1ba412752912a2c2c454958/ai/MrboomHelper.cpp#L455-L456

I think it should be `return(m.victoires[player & ~1]);`
- white = 0-1
- red = 2-3
- blue = 4-5
- grey = 6-7

I checked the medals in memory and team color wins are stored in slots 0,2,4,6

____________________________________________________

https://github.com/Javanaise/mrboom-libretro/blob/e074bafa1fe9480df1ba412752912a2c2c454958/ai/MrboomHelper.cpp#L465-L466

This might be wrong too since you can have humans (0-3) and bots (4-7). Medals are given to first bot it finds.

**Comment by frranck** [comment]
seems it's putting all victories for humans in 0 and for AI in 1.
